# 🐳 Docker Compose Configuration

version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LOCAL_AGENT_ENDPOINT=http://local-agent:8001/chat
      - DATABASE_URL=postgresql://benchmark_user:benchmark_password@postgres:5432/benchmark_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
    volumes:
      - ./data:/app/data
    networks:
      - benchmark-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - benchmark-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: benchmark_db
      POSTGRES_USER: benchmark_user
      POSTGRES_PASSWORD: benchmark_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - benchmark-network
    restart: unless-stopped

  local-agent:
    build:
      context: .
      dockerfile: Dockerfile.local-agent
    ports:
      - "8001:8001"
    networks:
      - benchmark-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - benchmark-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - benchmark-network
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:
  prometheus_data:

networks:
  benchmark-network:
    driver: bridge