# 📁 k8s/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: benchmark-service-account
  namespace: benchmark-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: benchmark-service-role
  namespace: benchmark-service
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: benchmark-service-role-binding
  namespace: benchmark-service
subjects:
- kind: ServiceAccount
  name: benchmark-service-account
  namespace: benchmark-service
roleRef:
  kind: Role
  name: benchmark-service-role
  apiGroup: rbac.authorization.k8s.io